// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Context;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20230816130211_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.DTO.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tel Aviv Ibn Gabirol",
                            DisplayName = "Ibn Gabirol"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ashdod big",
                            DisplayName = "Big Outlet"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Eilat",
                            DisplayName = "Ice Mall Eilat"
                        });
                });

            modelBuilder.Entity("api.Models.DTO.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "sandwiches"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "focaccia"
                        });
                });

            modelBuilder.Entity("api.Models.DTO.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PickUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("api.Models.DTO.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("api.Models.DTO.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisplayOnStore")
                        .HasColumnType("bit");

                    b.Property<string>("MainPicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(5451),
                            Description = "Fresh baked bread with Fresh Mozarela , tomato , and basil",
                            DisplayName = "Caprese Salad",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 22f
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(6332),
                            Description = "Fresh baked bread with Tuna Salad , tomato , and cucumaber",
                            DisplayName = "Tuna Salad",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 22f
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(6339),
                            Description = "Fresh baked bread with Egg Salad, Letuce and pickles",
                            DisplayName = "Egg Salad",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 22f
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(6341),
                            Description = "Fresh baked croissant with Salmon, Letuce and pickles",
                            DisplayName = "Salmon Croissant",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 25f
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(6344),
                            Description = "Small Pizza focaccia",
                            DisplayName = "Pizza focaccia",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 6f
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(6346),
                            Description = "Medium Pizza focaccia",
                            DisplayName = "Pizza focaccia",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 15f
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(6348),
                            Description = "Large Pizza focaccia",
                            DisplayName = "Pizza focaccia",
                            DisplayOnStore = true,
                            MainPicturePath = "",
                            Price = 22f
                        });
                });

            modelBuilder.Entity("api.Models.DTO.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthdayDate = new DateTime(2023, 8, 16, 16, 2, 11, 594, DateTimeKind.Local).AddTicks(2177),
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(3692),
                            Email = "admin@admin.com",
                            Firstname = "admin",
                            IsAdmin = true,
                            Lastname = "admin",
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PhoneCountryCode = "+972",
                            PhoneNumber = "0541230123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BirthdayDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(4528),
                            CreatedDate = new DateTime(2023, 8, 16, 16, 2, 11, 596, DateTimeKind.Local).AddTicks(4534),
                            Email = "test@test.com",
                            Firstname = "test",
                            IsAdmin = false,
                            Lastname = "test",
                            Password = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            PhoneCountryCode = "+972",
                            PhoneNumber = "0541230124",
                            Username = "test"
                        });
                });

            modelBuilder.Entity("api.Models.DTO.Order", b =>
                {
                    b.HasOne("api.Models.DTO.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("api.Models.DTO.Product", b =>
                {
                    b.HasOne("api.Models.DTO.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Models.DTO.Branch", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("api.Models.DTO.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
